"""The narrow backend contract used by guarded Calendar tools."""

from collections.abc import Awaitable
from datetime import datetime
from typing import Protocol, runtime_checkable

from .models import CalendarRef, ChangeRequest, EventRef


@runtime_checkable
class CalendarBackend(Protocol):
    def permission_status(self) -> Awaitable[str]: ...
    def list_calendars(self) -> Awaitable[list[CalendarRef]]: ...
    def read_events(self, calendar_ids: set[str], start: datetime, end: datetime) -> Awaitable[list[EventRef]]: ...
    def free_slots(self, calendar_ids: set[str], start: datetime, end: datetime) -> Awaitable[list[tuple[datetime, datetime]]]: ...
    def get_event(self, event_id: str) -> Awaitable[EventRef | None]: ...
    def create(self, request: ChangeRequest) -> Awaitable[EventRef]: ...
    def update(self, event: EventRef, request: ChangeRequest, scope: str | None) -> Awaitable[EventRef]: ...
    def delete(self, event: EventRef, scope: str | None) -> Awaitable[None]: ...
